spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.136.209:3306/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
# 配置日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
